name: Release
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: |
          yarn
      - name: Build Project
        run: |
          yarn build
          yarn next export
          mkdir gaianet-node
          cd ./gaianet-node
          pwd

      - name: Clone target repository
        uses: actions/checkout@v4
        with:
          repository: GaiaNet-AI/gaianet-node

      - name: Copy build files
        run: |
          pwd
          ls ../
          cp -r ../out/* ./dashboard/chatbot-ui/

      - name: Commit and push changes
        run: |
          git config --local user.email "juyichen0413@gmail.com"
          git config --local user.name "Gaianet worker"
          git add .
          git commit -m "Build and deploy chatbot-ui"
          git push