name: Release
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn

      - name: Build Project
        run: |
          yarn build
          yarn next export

      - name: Clone target repository
        run: git clone https://github.com/GaiaNet-AI/gaianet-node.git

      - name: Copy build files
        run: |
          cd gaianet-node
          cp -r ../out/* ./dashboard/chatbot-ui
          cd ./dashboard/chatbot-ui
          mv index.html chatbot-ui.html

      - name: Create index.html
        run: |
          echo "<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta charset="UTF-8"><meta http-equiv="refresh" content="0; URL=/chatbot-ui"><title>Redirecting...</title></head><body><p>If you are not redirected automatically, follow <a href="/chatbot-ui">this link</a>.</p></body></html>" > index.html
          echo "<head>" >> index.html
          echo "  <meta charset="UTF-8">" >> index.html
          echo "    <title>Hello, World!</title>" >> index.html
          echo "  </head>" >> index.html
          echo "  <body>" >> index.html
          echo "    <h1>Hello, World!</h1>" >> index.html
          echo "  </body>" >> index.html
          echo "</html>" >> index.html

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd gaianet-node
          git remote set-url --push origin https://JYC0413:$GITHUB_TOKEN@github.com/GaiaNet-AI/gaianet-node.git
          git config --local user.email "juyichen0413@foxmail.com"
          git config --global user.name "JYC0413"
          git add .
          git commit -m "Build and deploy chatbot-ui"
          git push